[book]
authors = ["Igor Anpilogov"]
language = "en"
multilingual = false
src = "src"
title = "Anomaly Modding Book"

[output.html]
git-repository-url = "https://github.com/Igigog/anomaly-modding-book"
site-url = "/anomaly-modding-book/"
additional-css = ["src/custom.css"]

# Tag Preprocessor https://github.com/dylanowen/mdbook-tag

[preprocessor.tag]
command = "mdbook-tag"
# Optional key to customize the output filename (defaults to tags.md)
filename = "customtagsfile.md"

# Table of contents preprocessor https://github.com/slowsage/mdbook-pagetoc

[preprocessor.pagetoc]
[output.html]
additional-css = ["src/pagetoc.css"]
additional-js  = ["src/pagetoc.js"]