[book]
authors = ["Igor Anpilogov"]
language = "en"
multilingual = false
src = "src"
title = "Anomaly Modding Book"

[output.html]
git-repository-url = "https://github.com/Igigog/anomaly-modding-book"
site-url = "/anomaly-modding-book/"
edit-url-template = "https://github.com/Igigog/anomaly-modding-book/edit/main/{path}"
additional-css = ["src/custom.css"]

[output.html.fold]
enable = true
level = 16